// Automatisch erzeugt von scripts/import_newsletter.py. Nicht von Hand bearbeiten.
export const NEWSLETTERPLAN = {
  "title": "Newsletter-Plan Q4 2026",
  "intro": "Quartal: Q4 2026. Rhythmus: wöchentlich (1 Ausgabe pro KW), Versand Di oder Do um 9:00 Uhr, zeitgleich zum passenden Social-Media-Post.",
  "source": "Newsletter-Plan_Q4_2026.xlsx",
  "stand": "2026-10-04",
  "steps": [
    "1. Ausgabe lesen und Status auf Freigegeben setzen (Freigabe: Darien).",
    "2. Rot markierte Platzhalter [DATUM] / [ZEITEN] vorher ausfüllen.",
    "3. In MailPoet: Vorlage öffnen, Betreff und Vorschautext einsetzen, Text und Button übernehmen, Bild einfügen, Versand auf Datum/Uhrzeit einplanen. Status: In MailPoet eingeplant.",
    "4. Nach dem Versand Status auf Versendet setzen und nach ca. 7 Tagen Öffnungsrate, Klickrate und Abmeldungen aus MailPoet eintragen. Die nächste Quartalsplanung wertet diese Spalten aus."
  ],
  "sources": [
    "BAU 11. bis 15.01.2027: bau-muenchen.com (abgerufen 04.10.2026)",
    "Ambiente 29.01. bis 02.02.2027: ambiente.messefrankfurt.com (abgerufen 04.10.2026)",
    "ISM 31.01. bis 03.02.2027: ism-cologne.de (abgerufen 04.10.2026)",
    "didacta 23. bis 27.02.2027: didacta-hannover.de (abgerufen 04.10.2026)",
    "INTERNORGA 12. bis 16.03.2027: internorga.com (abgerufen 04.10.2026)",
    "ISH 15. bis 19.03.2027: ish.messefrankfurt.com (abgerufen 04.10.2026)",
    "LogiMAT 16. bis 18.03.2027: logimat-messe.de (abgerufen 04.10.2026)",
    "HANNOVER MESSE 05. bis 08.04.2027: hannovermesse.de, Öffnungszeiten (abgerufen 04.10.2026)",
    "Druckdaten-Anforderungen: zipperwalls.de/kundenservice/faq-druckdaten/ und /druckinformationen/"
  ],
  "types": [
    {
      "name": "gekoppelt",
      "count": 12
    },
    {
      "name": "eigenständig",
      "count": 1
    }
  ],
  "entries": [
    {
      "nr": 1,
      "kw": 41,
      "date": "2026-10-08",
      "day": "Donnerstag",
      "time": "09:00",
      "type": "gekoppelt",
      "social": "Post 02: Messe-Tipp #01 Frühjahrsmessen 2027 jetzt planen",
      "rubric": "Ratgeber",
      "topic": "Start des Newsletters + Messe-Tipp #01: Frühjahrsmessen 2027 jetzt planen",
      "subject": "Frühjahrsmesse 2027? Jetzt ist der richtige Zeitpunkt",
      "subject_alt": "Messe-Tipp #01: Drei Schritte für Ihre Frühjahrsmesse",
      "preview": "Warum die Messen von Januar bis März im Herbst entschieden werden und was Sie jetzt erledigen sollten.",
      "text": "Guten Tag,\n\nab sofort erhalten Sie von uns jede Woche einen kurzen Newsletter mit Praxiswissen rund um Ihren Messeauftritt: Tipps zur Planung, Neuigkeiten aus dem Sortiment und Termine, die Sie kennen sollten. Kurz, sachlich und ohne Werbeflut.\n\nDen Anfang macht ein Thema, das viele Aussteller erst im Dezember bemerken: Die Frühjahrsmessen 2027 entscheiden sich jetzt.\n\nMESSE-TIPP #01: DREI SCHRITTE BIS JAHRESENDE\n\n1. Standmaße und Standart klären. Ob Reihen-, Eck- oder Kopfstand bestimmt, welche Seiten sichtbar sind und wie viele Wände und Theken Sie brauchen. Erst mit verbindlichen Maßen lässt sich die Ausstattung sinnvoll planen.\n\n2. Druckdaten mit Vorlauf anlegen. Planen Sie mindestens eine Korrekturschleife ein. Die Produktionszeit beginnt erst, wenn druckfähige Daten vorliegen und der Korrekturabzug freigegeben ist.\n\n3. Lieferzeit und Probeaufbau einplanen. Bauen Sie Ihren Stand einmal im eigenen Haus auf. So sehen Sie das Motiv in Originalgröße und wissen am Messetag, welcher Handgriff wohin gehört.\n\nWer diese drei Punkte bis Jahresende abhakt, startet entspannt in die Messesaison. Wenn Sie bei Größe, System oder Gestaltung unsicher sind, beraten wir Sie gern persönlich.\n\nViele Grüße aus Herxheim\nIhr Team von Zipperwalls\n\nTelefon +49 7276 4049970 (Montag bis Freitag, 8 bis 17 Uhr)\nkontakt@zipperwalls.de | www.zipperwalls.de",
      "button_text": "Messestände ansehen",
      "button_link": "https://www.zipperwalls.de/messestaende/",
      "extra_title": "Nächste Woche im Newsletter",
      "extra_text": "Fernwirkung: So gestalten Sie Ihre Messewand, damit Besucher Ihre Botschaft schon aus zehn Metern verstehen.",
      "extra_link": null,
      "image_idea": "Grafik aus Post 02 (Social_Media/2026/KW 41/post-02-instagram-facebook.png) oder Produktbild eines Messestand-Sets.",
      "note": "Erste Ausgabe nach langer Pause: Vor dem Versand Empfängerliste in MailPoet prüfen (nur Abonnenten mit Einwilligung).",
      "status": "Entwurf",
      "open_rate": null,
      "click_rate": null,
      "unsubscribes": null
    },
    {
      "nr": 2,
      "kw": 42,
      "date": "2026-10-13",
      "day": "Dienstag",
      "time": "09:00",
      "type": "eigenständig",
      "social": "kein direkter Bezug (Zusatzblock zu Post 25: Hinter den Kulissen, Bestellablauf)",
      "rubric": "Gestaltung",
      "topic": "Fernwirkung: So gestalten Sie eine Messewand, die aus zehn Metern wirkt",
      "subject": "Fernwirkung: Fünf Regeln für Ihre Messewand",
      "subject_alt": "Wirkt Ihre Messewand auch aus zehn Metern?",
      "preview": "Besucher entscheiden in Sekunden. So gestalten Sie ein Motiv, das im Gang auffällt und sofort verstanden wird.",
      "text": "Guten Tag,\n\nBesucher entscheiden im Vorbeigehen, ob sie stehen bleiben. Ihre Messewand hat dafür nur wenige Sekunden, und das oft aus mehreren Metern Entfernung. Mit diesen fünf Regeln wirkt Ihr Motiv auch aus zehn Metern.\n\nFÜNF REGELN FÜR FERNWIRKUNG\n\n1. Eine Wand, eine Botschaft. Formulieren Sie eine Kernaussage in wenigen Worten, die sofort klar macht, was Sie anbieten. Details gehören in das Gespräch oder auf den Flyer, nicht auf die Rückwand.\nTipp: Testen Sie die Aussage am Kollegen. Versteht er in drei Sekunden, worum es geht, passt sie.\n\n2. Wichtiges nach oben. Logo und Kernaussage gehören in den oberen Bereich der Wand. Theke, Möbel und Besucher verdecken den unteren Teil fast immer.\nTipp: Lassen Sie im unteren Bereich Platz für Bildfläche statt Text.\n\n3. Groß und klar schreiben. Wählen Sie eine gut lesbare Schrift ohne Verzierungen und eine Schriftgröße, die auch aus der Entfernung lesbar ist. Lieber weniger Text, dafür größer.\nTipp: Drucken Sie den Entwurf auf A4 aus und betrachten Sie ihn aus drei Metern. Was dort schwer lesbar ist, ist es auf der Messe auch.\n\n4. Starker Kontrast. Dunkle Schrift auf hellem Grund oder helle Schrift auf dunklem Grund. Text direkt auf unruhigen Fotos geht in der Halle unter.\n\n5. Ein großes Bild statt vieler kleiner. Ein starkes Motiv zieht mehr Blicke an als eine Collage. Achten Sie auf mindestens 120 dpi in Endgröße, damit nichts unscharf wirkt.\n\nWenn Sie bei der Gestaltung Unterstützung möchten, übernimmt unser Grafikservice Layout und Datenprüfung.\n\nViele Grüße\nIhr Team von Zipperwalls",
      "button_text": "Zum Grafikservice",
      "button_link": "https://www.zipperwalls.de/grafikservice/",
      "extra_title": "Heute auf unseren Kanälen",
      "extra_text": "Von der Idee zur fertigen Messewand: wie eine Bestellung bei uns abläuft.",
      "extra_link": null,
      "image_idea": "Produktfoto einer bedruckten Messewand mit klarem, großem Motiv aus dem Shop.",
      "note": "Thema am 04.10.2026 geändert (Wunsch Bela/Darien): kein Messekalender, kein Bestellablauf. Eigenständige Ausgabe zur Gestaltung.",
      "status": "Entwurf",
      "open_rate": null,
      "click_rate": null,
      "unsubscribes": null
    },
    {
      "nr": 3,
      "kw": 43,
      "date": "2026-10-20",
      "day": "Dienstag",
      "time": "09:00",
      "type": "gekoppelt",
      "social": "Post 05: Messe-Tipp #02 Der Motten-Effekt",
      "rubric": "Ratgeber",
      "topic": "Messe-Tipp #02: Der Motten-Effekt, warum Licht Besucher anzieht",
      "subject": "Der Motten-Effekt: Warum Licht Besucher anzieht",
      "subject_alt": "Messe-Tipp #02: So wird Ihr Stand im Gang gesehen",
      "preview": "In gleichmäßig ausgeleuchteten Hallen fällt auf, was selbst leuchtet. So nutzen Sie den Effekt für Ihren Stand.",
      "text": "Guten Tag,\n\nMessehallen sind hell, gleichmäßig ausgeleuchtet und voller Reize. Besucher entscheiden in wenigen Sekunden, wo sie stehen bleiben. Was dabei zuverlässig Aufmerksamkeit bekommt: Flächen, die selbst leuchten.\n\nMESSE-TIPP #02: DER MOTTEN-EFFEKT\n\nWir nennen das den Motten-Effekt. Eine hinterleuchtete Rückwand setzt sich von der Umgebung ab, wirkt hochwertig und ist schon aus dem Gang erkennbar. Drei Punkte, auf die es ankommt:\n\n1. Gleichmäßige Ausleuchtung. Gute LED-Textilwände leuchten die ganze Fläche aus, ohne helle Flecken und ohne zu blenden.\n\n2. Ein klares Motiv. Licht verstärkt, was zu sehen ist. Eine Botschaft und ein starkes Bild wirken besser als viele Details.\n\n3. Die richtige Position. Die leuchtende Fläche gehört dorthin, wo sie vom Hauptgang aus gesehen wird, meist an die Rückwand oder als Blickfang an die Standecke.\n\nUnser Ratgeber zeigt ausführlicher, wie Sie Licht gezielt einsetzen und welche Systeme sich für welche Standgröße eignen.\n\nViele Grüße aus Herxheim\nIhr Team von Zipperwalls\n\nTelefon +49 7276 4049970 (Montag bis Freitag, 8 bis 17 Uhr)\nkontakt@zipperwalls.de | www.zipperwalls.de",
      "button_text": "Zum Ratgeber Motten-Effekt",
      "button_link": "https://www.zipperwalls.de/wissen/ratgeber/messestand-besucher-anziehen-motten-effekt/",
      "extra_title": "Am Donnerstag auf unseren Kanälen: LED-Messewände und PIXLIP GO",
      "extra_text": "Modulare Lightbox-Systeme verbinden gleichmäßige Hinterleuchtung mit werkzeuglosem Aufbau. Einzelne Module lassen sich zu größeren Wänden kombinieren und für den nächsten Auftritt neu bespannen.",
      "extra_link": "https://www.zipperwalls.de/messewaende/led-messewaende/",
      "image_idea": "Grafik aus Post 05 (KW 43) oder Produktbild einer LED-Messewand von zipperwalls.de.",
      "note": null,
      "status": "Entwurf",
      "open_rate": null,
      "click_rate": null,
      "unsubscribes": null
    },
    {
      "nr": 4,
      "kw": 44,
      "date": "2026-10-29",
      "day": "Donnerstag",
      "time": "09:00",
      "type": "gekoppelt",
      "social": "Post 08: Grafikservice (Zusatzblock zu Post 07: Messe-Tipp #03)",
      "rubric": "Service",
      "topic": "Druckdaten richtig anlegen: 6 Punkte vor dem Upload + Grafikservice",
      "subject": "Druckdaten ohne Rückfragen: 6 Punkte vor dem Upload",
      "subject_alt": "So kommen Ihre Druckdaten beim ersten Mal durch",
      "preview": "Der häufigste Engpass vor der Messe sind die Druckdaten. Mit dieser Liste sparen Sie Korrekturschleifen.",
      "text": "Guten Tag,\n\naus der Praxis wissen wir: Vor der Messe wird selten das System knapp, sondern die Zeit für die Druckdaten. Jede Rückfrage kostet Tage. Mit diesen sechs Punkten kommen Ihre Daten beim ersten Mal durch.\n\n1. Erst bestellen, dann Daten senden. Geben Sie bei jeder Datenlieferung Ihre Bestellnummer an, damit wir die Dateien eindeutig zuordnen können.\n\n2. Die passende Druckvorlage verwenden. Auf jeder Produktseite finden Sie unter \"Druckvorlagen\" das Datenblatt mit Endformat und allen Maßen.\n\n3. Im Farbmodus CMYK anlegen. RGB-Daten werden automatisch umgewandelt, dabei kann es zu Farbverschiebungen kommen.\n\n4. Auf die Bildauflösung achten. Bilder sollten in Endgröße mindestens 120 dpi haben. Ist die Auflösung zu gering, melden wir uns vor dem Druck bei Ihnen.\n\n5. Schriften in Pfade umwandeln und keine Word- oder PowerPoint-Dateien senden. Diese Formate sind für den Druck nicht geeignet.\n\n6. Den Korrekturabzug zügig freigeben. Sie erhalten von uns ein Ansichts-PDF. Erst mit Ihrer schriftlichen Freigabe beginnt die Produktion.\n\nGroße Dateien senden Sie am einfachsten über zipperwalls.wetransfer.com, kleinere per E-Mail an daten@zipperwalls.de (bis 25 MB).\n\nKEINE DRUCKDATEN ODER KEINE ZEIT?\n\nUnser Grafikservice gestaltet Ihr Layout nach Ihren Vorgaben (45 € je halbe Stunde) oder passt vorhandene Daten an die Druckvorlage an (25 € je Datei, jeweils zzgl. MwSt.).\n\nViele Grüße aus Herxheim\nIhr Team von Zipperwalls\n\nTelefon +49 7276 4049970 (Montag bis Freitag, 8 bis 17 Uhr)\nkontakt@zipperwalls.de | www.zipperwalls.de",
      "button_text": "Zum Grafikservice",
      "button_link": "https://www.zipperwalls.de/grafikservice/",
      "extra_title": "Messe-Tipp #03 dieser Woche: der komplette Stand im PKW",
      "extra_text": "Textile Messesysteme lassen sich zerlegt im Kombi transportieren: Rahmen in Tasche oder Trolley, Drucke gefaltet. Das spart Spedition, Lagerfläche und feste Anlieferzeiten.",
      "extra_link": "https://www.zipperwalls.de/wissen/ratgeber/messestand-transportieren-logistik-kosten-senken/",
      "image_idea": "Grafik aus Post 08 (KW 44) oder Ausschnitt einer Druckvorlage (Datenblatt) aus dem Shop.",
      "note": "Grafikservice-Preise prüfen (Stand 08/2026). 120 dpi und Schriften in Pfade sind interne Preflight-Vorgaben, vor Versand bestätigen. Druckdaten-Upload im Checkout noch nicht live, deshalb nicht erwähnt.",
      "status": "Entwurf",
      "open_rate": null,
      "click_rate": null,
      "unsubscribes": null
    },
    {
      "nr": 5,
      "kw": 45,
      "date": "2026-11-03",
      "day": "Dienstag",
      "time": "09:00",
      "type": "gekoppelt",
      "social": "Post 09: Messe-Tipp #04 Mieten oder kaufen?",
      "rubric": "Ratgeber",
      "topic": "Messe-Tipp #04: Messestand mieten oder kaufen?",
      "subject": "Messestand mieten oder kaufen? Unsere Faustregel",
      "subject_alt": "Messe-Tipp #04: Ab wann sich ein eigenes System lohnt",
      "preview": "Eine Frage aus fast jeder Beratung. Diese vier Punkte gehören in einen fairen Vergleich.",
      "text": "Guten Tag,\n\nmieten oder kaufen? Diese Frage hören wir in fast jeder Beratung. Eine pauschale Antwort gibt es nicht, aber eine einfache Faustregel: Je häufiger Sie ausstellen, desto eher lohnt sich ein eigenes System.\n\nMESSE-TIPP #04: VIER PUNKTE FÜR DEN VERGLEICH\n\n1. Anzahl der Einsätze. Rechnen Sie nicht nur die nächste Messe, sondern alle Termine der kommenden zwei bis drei Jahre, inklusive Hausmessen, Kundenevents und Showroom.\n\n2. Laufende Kosten. Zur Miete kommen meist Transport sowie Auf- und Abbau. Beim Kauf gehören Lagerung und Transport fair mit in die Rechnung.\n\n3. Flexibilität. Bei textilen Systemen bleibt der Aluminiumrahmen, nur der Stoffdruck wechselt. Eine neue Kampagne kostet dann einen Ersatzdruck, keinen neuen Stand.\n\n4. Verfügbarkeit. Ein eigenes System steht jederzeit bereit, auch für einen kurzfristigen Zusatztermin.\n\nDie ausführliche Gegenüberstellung finden Sie in unserem Ratgeber.\n\nViele Grüße aus Herxheim\nIhr Team von Zipperwalls\n\nTelefon +49 7276 4049970 (Montag bis Freitag, 8 bis 17 Uhr)\nkontakt@zipperwalls.de | www.zipperwalls.de",
      "button_text": "Zum Ratgeber Mieten oder kaufen",
      "button_link": "https://www.zipperwalls.de/wissen/ratgeber/messestand-mieten-oder-kaufen-vergleich/",
      "extra_title": "Am Donnerstag auf unseren Kanälen: Ersatzdrucke",
      "extra_text": "Neue Kampagne, gleiches System: Passende Ersatzdrucke gibt es für nahezu alle Systeme im Shop. Gedruckt wird im Sublimationsverfahren ohne Lösungs- und Bindemittel.",
      "extra_link": "https://www.zipperwalls.de/messewaende/ersatzdrucke/",
      "image_idea": "Grafik aus Post 09 (KW 45).",
      "note": "Keine steuerlichen Aussagen (Abschreibung o.ä.). Faustregel mit dem Ratgeber-Artikel abgleichen.",
      "status": "Entwurf",
      "open_rate": null,
      "click_rate": null,
      "unsubscribes": null
    },
    {
      "nr": 6,
      "kw": 46,
      "date": "2026-11-12",
      "day": "Donnerstag",
      "time": "09:00",
      "type": "gekoppelt",
      "social": "Post 12: So entsteht Ihr Stoffdruck (Zusatzblock zu Post 11: Outdoor im Winter)",
      "rubric": "Hinter den Kulissen",
      "topic": "So entsteht Ihr Stoffdruck + Pflege und Lagerung nach der Messesaison",
      "subject": "Nach der Messe: So bleibt Ihr Stoffdruck wie neu",
      "subject_alt": "Wie Ihr Messedruck entsteht und wie Sie ihn pflegen",
      "preview": "Ein Blick auf den Sublimationsdruck und fünf Handgriffe für Pflege und Lagerung nach der Saison.",
      "text": "Guten Tag,\n\ndie Herbstmessen sind vorbei, viele Messestände wandern jetzt ins Lager. Ein guter Moment für einen Blick darauf, wie Ihr Stoffdruck entsteht und wie er lange gut aussieht.\n\nSO ENTSTEHT IHR DRUCK\n\nWir drucken unsere Textilien im Sublimationsverfahren, ohne Lösungs- und Bindemittel. Die Farbe verbindet sich dabei mit der Faser, statt als Schicht auf dem Stoff zu liegen. Das Ergebnis sind brillante Farben und eine knitterarme Oberfläche, die bei 30 °C waschbar ist. Der Stretch-Display-Stoff ist B1-zertifiziert und damit für den Einsatz in Messehallen geeignet.\n\nFÜNF HANDGRIFFE NACH DER MESSE\n\n1. Stoffbezug abnehmen und auf Flecken prüfen. Bei Bedarf bei 30 °C waschen und die Pflegehinweise zum Produkt beachten.\n\n2. Den Druck vollständig trocknen lassen, bevor er eingepackt wird.\n\n3. Rahmenteile auf Vollständigkeit prüfen und Fehlendes gleich nachbestellen, nicht erst kurz vor der nächsten Messe.\n\n4. Den Druck locker gefaltet in der Tasche lagern, trocken und nicht unter schweren Gegenständen.\n\n5. Notieren, was beim letzten Aufbau gefehlt hat, vom Verlängerungskabel bis zum Prospektständer.\n\nUnd wenn Ihr Motiv nicht mehr aktuell ist: Tauschen Sie einfach den Druck. Der Rahmen bleibt.\n\nViele Grüße aus Herxheim\nIhr Team von Zipperwalls\n\nTelefon +49 7276 4049970 (Montag bis Freitag, 8 bis 17 Uhr)\nkontakt@zipperwalls.de | www.zipperwalls.de",
      "button_text": "Ersatzdrucke ansehen",
      "button_link": "https://www.zipperwalls.de/messewaende/ersatzdrucke/",
      "extra_title": "Diese Woche auf unseren Kanälen: Outdoor im Winter",
      "extra_text": "Für Weihnachtsmärkte, Winterevents und Aktionstage führen wir bedruckte Faltzelte, Beachflags, Werbetore und aufblasbare Zelte. Wer im Dezember draußen sichtbar sein will, sollte die Lieferzeit jetzt einplanen.",
      "extra_link": "https://www.zipperwalls.de/outdoor/",
      "image_idea": "Grafik aus Post 12 (KW 46); falls vorhanden eigenes Foto vom Druck oder vom Lager.",
      "note": "Pflegehinweise (Waschen, Trocknen, Lagerung) mit Herstellerangaben abgleichen. Pflegeteil ist eigenständiger Inhalt, nicht auf Social Media.",
      "status": "Entwurf",
      "open_rate": null,
      "click_rate": null,
      "unsubscribes": null
    },
    {
      "nr": 7,
      "kw": 47,
      "date": "2026-11-17",
      "day": "Dienstag",
      "time": "09:00",
      "type": "gekoppelt",
      "social": "Post 13: Messe-Tipp #05 Leadgenerierung",
      "rubric": "Ratgeber",
      "topic": "Messe-Tipp #05: Leadgenerierung, drei Regeln fürs Nachfassen",
      "subject": "Messe vorbei, Kontakte gesichert? 3 Regeln fürs Nachfassen",
      "subject_alt": "Messe-Tipp #05: Aus Gesprächen werden Kunden",
      "preview": "Der Erfolg einer Messe entscheidet sich danach. So machen Sie aus Gesprächen verwertbare Kontakte.",
      "text": "Guten Tag,\n\nein voller Stand ist ein gutes Gefühl. Ob sich die Messe gelohnt hat, zeigt sich aber erst in den Wochen danach. Drei Regeln, die wir Ausstellern empfehlen:\n\nMESSE-TIPP #05: LEADGENERIERUNG, DIE NACH DER MESSE ZÄHLT\n\n1. Ein messbares Ziel pro Messetag. Zum Beispiel eine bestimmte Zahl qualifizierter Gespräche oder vereinbarter Folgetermine. So weiß das Standteam, worauf es ankommt.\n\n2. Gesprächsinhalte direkt am Stand erfassen. Name, Bedarf, nächster Schritt, Zeitrahmen. Was abends aus dem Gedächtnis notiert wird, ist meist unvollständig.\n\n3. Innerhalb von 48 Stunden nachfassen. Eine persönliche E-Mail mit Bezug auf das Gespräch wirkt mehr als ein allgemeines Rundschreiben Wochen später.\n\nEin Tipp aus der Praxis: Planen Sie am Stand einen ruhigen Platz für Gespräche ein, etwa eine Theke mit Ablage. Wer Platz zum Notieren hat, notiert auch.\n\nMehr zu Zielen, Gesprächsführung und Nachbereitung lesen Sie in unserem Ratgeber.\n\nViele Grüße aus Herxheim\nIhr Team von Zipperwalls\n\nTelefon +49 7276 4049970 (Montag bis Freitag, 8 bis 17 Uhr)\nkontakt@zipperwalls.de | www.zipperwalls.de",
      "button_text": "Zum Ratgeber Leadgenerierung",
      "button_link": "https://www.zipperwalls.de/wissen/ratgeber/leadgenerierung-auf-der-messe/",
      "extra_title": "Am Donnerstag auf unseren Kanälen: Messestand-Sets",
      "extra_text": "Unsere Sets kombinieren Messewand und Theke in einem Design, inklusive Druck. Erhältlich als Reihen-, Eck- oder Kopfstand, von kompakten 3 x 3 m bis zu großen Flächen mit Kabine.",
      "extra_link": "https://www.zipperwalls.de/messestaende/",
      "image_idea": "Grafik aus Post 13 (KW 47).",
      "note": null,
      "status": "Entwurf",
      "open_rate": null,
      "click_rate": null,
      "unsubscribes": null
    },
    {
      "nr": 8,
      "kw": 48,
      "date": "2026-11-26",
      "day": "Donnerstag",
      "time": "09:00",
      "type": "gekoppelt",
      "social": "Post 16: Jahresende, Messejahr 2027 einplanen (Zusatzblock zu Post 15: Messe-Tipp #06)",
      "rubric": "Saison",
      "topic": "Jahresende: Messejahr 2027 planen, Ausstattung für mehrere Saisons",
      "subject": "Messejahr 2027: Jetzt planen, entspannt starten",
      "subject_alt": "Ihr Messebudget 2027 sinnvoll einsetzen",
      "preview": "Viele Unternehmen planen jetzt das Marketingbudget für 2027. So wird daraus eine Ausstattung für mehrere Saisons.",
      "text": "Guten Tag,\n\nzum Jahresende planen viele Unternehmen ihr Marketingbudget für das kommende Jahr. Wenn Messen dazugehören, lohnt sich ein Blick über die nächste Veranstaltung hinaus.\n\nEINE INVESTITION ÜBER MEHRERE SAISONS\n\nAluminiumrahmen und Theken bleiben über Jahre im Einsatz, nur die Drucke wechseln mit der Kampagne. Wer in ein durchdachtes System investiert, plant damit nicht eine Messe, sondern ein ganzes Messejahr.\n\nDREI FRAGEN FÜR IHRE PLANUNG\n\n1. Welche Termine stehen 2027 fest, und welche kommen erfahrungsgemäß kurzfristig dazu?\n\n2. Welche Standgrößen brauchen Sie? Modulare Systeme lassen sich für kleine und große Flächen kombinieren.\n\n3. Was ist schon vorhanden? Bestehende Rahmen bekommen mit einem Ersatzdruck ein neues Gesicht.\n\nWer jetzt bestellt, startet mit fertiger Ausstattung in die Frühjahrsmessen 2027. Gern stellen wir Ihnen ein Paket für Ihr Messejahr zusammen, abgestimmt auf Ihre Termine und Flächen.\n\nViele Grüße aus Herxheim\nIhr Team von Zipperwalls\n\nTelefon +49 7276 4049970 (Montag bis Freitag, 8 bis 17 Uhr)\nkontakt@zipperwalls.de | www.zipperwalls.de",
      "button_text": "Beratung anfragen",
      "button_link": "https://www.zipperwalls.de/kontakt/",
      "extra_title": "Messe-Tipp #06 dieser Woche: das Klick-Prinzip",
      "extra_text": "Rahmen zusammenstecken, Stoffbezug überziehen, Reißverschluss schließen, Füße montieren. Vier Schritte, kein Werkzeug, kein Messebauer.",
      "extra_link": "https://www.zipperwalls.de/wissen/ratgeber/messestand-schnell-aufbauen-ohne-werkzeug/",
      "image_idea": "Grafik aus Post 16 (KW 48).",
      "note": "Keine steuerlichen Aussagen. Black Friday (27.11.) bewusst nicht bespielt, kein Rabatt-Ton.",
      "status": "Entwurf",
      "open_rate": null,
      "click_rate": null,
      "unsubscribes": null
    },
    {
      "nr": 9,
      "kw": 49,
      "date": "2026-12-01",
      "day": "Dienstag",
      "time": "09:00",
      "type": "gekoppelt",
      "social": "Post 17: Messe-Tipp #07 Hausmesse im Januar",
      "rubric": "Ratgeber",
      "topic": "Messe-Tipp #07: Hausmesse im Januar planen",
      "subject": "Hausmesse im Januar? Jetzt Termin und Einladung festlegen",
      "subject_alt": "Messe-Tipp #07: Ihre eigene Messe im eigenen Haus",
      "preview": "Für viele Mittelständler der wichtigste Kundentermin des Jahres. So gelingt die Hausmesse mit wenig Aufwand.",
      "text": "Guten Tag,\n\ndie Hausmesse ist für viele Mittelständler der wichtigste Kundentermin im Jahr. Sie bestimmen Termin, Gästeliste und Atmosphäre, und Ihre Kunden erleben Ihr Unternehmen dort, wo es arbeitet.\n\nMESSE-TIPP #07: HAUSMESSE IM JANUAR PLANEN\n\n1. Termin und Einladungen jetzt festlegen. Im Dezember sind die Kalender Ihrer Kunden voll. Eine Einladung mit Vorlauf und eine Erinnerung im Januar sichern die Teilnahme.\n\n2. Räume in Themeninseln gliedern. Mit mobilen Messewänden und Theken entstehen in Halle, Werkstatt oder Foyer klar getrennte Bereiche, ganz ohne bauliche Veränderung.\n\n3. Wege planen. Begrüßung, Beschilderung, Stationen: Ihre Gäste sollen sich ohne Erklärung zurechtfinden.\n\n4. Die Ausstattung weiter nutzen. Was im Januar Ihre Hausmesse gliedert, steht danach im Empfang, im Showroom oder auf der nächsten Fachmesse.\n\nWeitere Tipps zu Planung, Ablauf und Nachbereitung finden Sie in unserem Ratgeber.\n\nViele Grüße aus Herxheim\nIhr Team von Zipperwalls\n\nTelefon +49 7276 4049970 (Montag bis Freitag, 8 bis 17 Uhr)\nkontakt@zipperwalls.de | www.zipperwalls.de",
      "button_text": "Zum Ratgeber Hausmesse",
      "button_link": "https://www.zipperwalls.de/wissen/ratgeber/hausmesse-planen/",
      "extra_title": "Auf der Suche nach Ideen? Messestand-Ideen aus der Praxis",
      "extra_text": "In unserem Ratgeber haben wir Beispiele und Anregungen für unterschiedliche Standgrößen zusammengestellt, vom kompakten Reihenstand bis zur großen Fläche.",
      "extra_link": "https://www.zipperwalls.de/wissen/ratgeber/messestand-ideen/",
      "image_idea": "Grafik aus Post 17 (KW 49).",
      "note": "Kundenstimme (Post 18, Do 03.12.) bewusst nicht im Newsletter, solange die Trusted-Shops-Bedingungen für Zitate nicht geprüft sind.",
      "status": "Entwurf",
      "open_rate": null,
      "click_rate": null,
      "unsubscribes": null
    },
    {
      "nr": 10,
      "kw": 50,
      "date": "2026-12-10",
      "day": "Donnerstag",
      "time": "09:00",
      "type": "gekoppelt",
      "social": "Post 20: Bestellschluss vor Weihnachten (dazu Post 19: Messe-Tipp #08)",
      "rubric": "Service",
      "topic": "Bestellschluss vor Weihnachten + Messe-Tipp #08: Kleiner Stand, große Wirkung",
      "subject": "Wichtig für Januar-Messen: Bestellschluss vor Weihnachten",
      "subject_alt": "Bis [DATUM] bestellen, vor dem Jahreswechsel geliefert",
      "preview": "Die Feiertage verkürzen die Produktionszeit. Diese Termine sollten Sie kennen, wenn Sie im Januar ausstellen.",
      "text": "Guten Tag,\n\nfür alle, die im Januar ausstellen: Die Feiertage verkürzen die Produktionszeit. Damit Ihre Messeausstattung vor dem Jahreswechsel bei Ihnen ist, gelten in diesem Jahr folgende Termine:\n\nBestellung bis: [DATUM]\nDruckfertige Daten und Freigabe des Korrekturabzugs bis: [DATUM]\n\nBitte beachten Sie: Die Lieferzeit beginnt mit der Freigabe des Korrekturabzugs. Planen Sie deshalb lieber eine Woche Puffer ein. Zur Lieferzeit einzelner Produkte beraten wir Sie gern persönlich.\n\nMESSE-TIPP #08: KLEINER STAND, GROSSE WIRKUNG\n\nGerade im Januar stehen viele Aussteller auf kompakten Flächen. Auf 6 bis 10 m² entscheidet die Reduktion:\n\n1. Eine Rückwand mit einem Motiv und einer Botschaft.\n\n2. Die Theke an der Gangkante, damit Gespräche dort beginnen, wo Besucher vorbeigehen.\n\n3. Die Höhe nutzen, damit der Stand schon von weitem erkennbar ist.\n\nViele Grüße aus Herxheim\nIhr Team von Zipperwalls\n\nTelefon +49 7276 4049970 (Montag bis Freitag, 8 bis 17 Uhr)\nkontakt@zipperwalls.de | www.zipperwalls.de",
      "button_text": "Messestände bis 10 m² ansehen",
      "button_link": "https://www.zipperwalls.de/messestaende/messestaende-10-m%c2%b2/",
      "extra_title": "Praxisbeispiele für kleine Stände",
      "extra_text": "Wie Sie auf 6 bis 10 Quadratmetern überzeugen, zeigt unser Ratgeber mit Beispielen und Vorher-Nachher-Bildern.",
      "extra_link": "https://www.zipperwalls.de/wissen/ratgeber/kleiner-messestand-design-tipps/",
      "image_idea": "Grafik aus Post 20 (KW 50).",
      "note": "OFFEN: Bestellschluss und Datenschluss vor Weihnachten mit Lieferanten klären und bei [DATUM] eintragen. Falls die Termine früher feststehen, Versand auf Di 08.12. vorziehen.",
      "status": "Entwurf",
      "open_rate": null,
      "click_rate": null,
      "unsubscribes": null
    },
    {
      "nr": 11,
      "kw": 51,
      "date": "2026-12-17",
      "day": "Donnerstag",
      "time": "09:00",
      "type": "gekoppelt",
      "social": "Post 22: Checkliste Messestand (Zusatzblock zu Post 21: Digital Signage)",
      "rubric": "Ratgeber",
      "topic": "Checkliste Messestand 2027 zum Abhaken",
      "subject": "Checkliste Messestand 2027 zum Abhaken",
      "subject_alt": "Was braucht man für einen Messestand? Die komplette Liste",
      "preview": "Grundausstattung, Organisation, Kommunikation, Team: die Liste für Ihre Planung über die Feiertage.",
      "text": "Guten Tag,\n\ndie ruhigeren Tage zum Jahresende eignen sich gut, um die Messesaison 2027 vorzubereiten. Damit nichts fehlt, haben wir unsere Checkliste für Sie zusammengefasst.\n\nGRUNDAUSSTATTUNG\nRückwand oder Messewand mit Ihrem Motiv\nTheke für Gespräche, Ablage und Stauraum\nBeleuchtung, zum Beispiel LED-Strahler oder eine hinterleuchtete Wand\nProspektständer für Ihre Unterlagen\n\nORGANISATION\nStromanschluss beim Veranstalter bestellen\nBodenbelag und Standreinigung klären\nTransport, Aufbau und Abbau planen\nProbeaufbau im eigenen Haus\n\nKOMMUNIKATION\nWerbemittel und Unterlagen\nDigitale Inhalte, etwa ein Bildschirm mit Produktvideo\nEinladungen an Kunden und ein Plan zum Nachfassen\n\nTEAM\nStandbesetzung und Pausen festlegen\nGesprächsleitfaden und Erfassung der Kontakte\n\nDie vollständige Liste mit Hinweisen zur Planung finden Sie in unserem Ratgeber.\n\nViele Grüße aus Herxheim\nIhr Team von Zipperwalls\n\nTelefon +49 7276 4049970 (Montag bis Freitag, 8 bis 17 Uhr)\nkontakt@zipperwalls.de | www.zipperwalls.de",
      "button_text": "Zur vollständigen Checkliste",
      "button_link": "https://www.zipperwalls.de/wissen/ratgeber/was-braucht-man-fuer-einen-messestand/",
      "extra_title": "Diese Woche auf unseren Kanälen: Digital Signage",
      "extra_text": "Digitale Infostelen ergänzen textile Messesysteme um bewegte Inhalte: Produktvideos, Referenzen oder Angebote, aktualisiert ohne Neudruck. Nach der Messe stehen sie im Empfang oder Showroom weiter im Einsatz.",
      "extra_link": "https://www.zipperwalls.de/digital-signage/",
      "image_idea": "Grafik aus Post 22 (KW 51).",
      "note": "Checkliste in MailPoet als Aufzählung mit Häkchen-Symbolen setzen.",
      "status": "Entwurf",
      "open_rate": null,
      "click_rate": null,
      "unsubscribes": null
    },
    {
      "nr": 12,
      "kw": 52,
      "date": "2026-12-22",
      "day": "Dienstag",
      "time": "09:00",
      "type": "gekoppelt",
      "social": "Post 23: Weihnachtsgruß und Servicezeiten",
      "rubric": "Über uns",
      "topic": "Weihnachtsgruß, Dank für 2026 und Servicezeiten zwischen den Jahren",
      "subject": "Danke für 2026 und unsere Servicezeiten",
      "subject_alt": "Frohe Feiertage aus Herxheim",
      "preview": "Ein kurzer Dank zum Jahresende und wann Sie uns zwischen den Jahren erreichen.",
      "text": "Guten Tag,\n\nein Jahr mit vielen Messeprojekten geht zu Ende. Wir haben zahlreiche Kunden auf dem Weg zu ihrem Messeauftritt begleitet, vom ersten Entwurf bis zur Lieferung. Dafür danken wir Ihnen, unseren Partnern und Lieferanten herzlich.\n\nSERVICEZEITEN ZWISCHEN DEN JAHREN\n\n[ZEITEN]\n\nAb [DATUM] sind wir wieder zu den gewohnten Zeiten für Sie da: Montag bis Freitag von 8 bis 17 Uhr.\n\nIn der nächsten Ausgabe erhalten Sie unseren Fahrplan für das Messejahr 2027, damit Sie gut vorbereitet ins neue Jahr starten.\n\nWir wünschen Ihnen und Ihrem Team erholsame Feiertage und einen guten Start in das Messejahr 2027.\n\nViele Grüße aus Herxheim\nIhr Team von Zipperwalls\n\nTelefon +49 7276 4049970 (Montag bis Freitag, 8 bis 17 Uhr)\nkontakt@zipperwalls.de | www.zipperwalls.de",
      "button_text": "Zum Shop",
      "button_link": "https://www.zipperwalls.de/",
      "extra_title": null,
      "extra_text": null,
      "extra_link": null,
      "image_idea": "Grafik aus Post 23 (KW 52); falls vorhanden ein Teamfoto.",
      "note": "OFFEN: Servicezeiten zwischen den Jahren und Datum des Wiederbeginns eintragen.",
      "status": "Entwurf",
      "open_rate": null,
      "click_rate": null,
      "unsubscribes": null
    },
    {
      "nr": 13,
      "kw": 53,
      "date": "2026-12-29",
      "day": "Dienstag",
      "time": "09:00",
      "type": "gekoppelt",
      "social": "Post 24: Ausblick Fahrplan Messejahr 2027",
      "rubric": "Ratgeber",
      "topic": "Fahrplan Messejahr 2027: vier Etappen bis zur nächsten Messe",
      "subject": "Ihr Fahrplan für das Messejahr 2027",
      "subject_alt": "Vier Etappen bis zur nächsten Messe",
      "preview": "Von der Flächenbuchung bis zum Probeaufbau: So bleibt vor jeder Messe Zeit für das Wesentliche.",
      "text": "Guten Tag,\n\nzum Abschluss des Jahres ein einfacher Fahrplan, mit dem Sie jede Messe 2027 planen können. Rechnen Sie dafür vom Messetermin rückwärts.\n\nJETZT: Messen auswählen und Flächen buchen. Gute Standplätze sind früh vergeben.\n\n12 WOCHEN VORHER: Standkonzept und Druckmotiv festlegen. Von wo aus wird Ihr Stand gesehen, und welche Botschaft soll hängen bleiben?\n\n6 WOCHEN VORHER: Bestellung aufgeben und Druckdaten liefern, inklusive Korrekturschleife.\n\n4 WOCHEN VORHER: Probeaufbau im eigenen Haus. So sehen Sie das Motiv in Originalgröße, und Ihr Team kennt jeden Handgriff.\n\nIN DER MESSEWOCHE: Material vollständig? Kontakterfassung vorbereitet? Termine zum Nachfassen im Kalender geblockt?\n\nSo bleibt vor Ort Zeit für das, was auf der Messe zählt: die Gespräche.\n\nAb Januar geht es hier mit neuen Messe-Tipps weiter. Wir freuen uns, wenn Sie dabei bleiben.\n\nViele Grüße aus Herxheim\nIhr Team von Zipperwalls\n\nTelefon +49 7276 4049970 (Montag bis Freitag, 8 bis 17 Uhr)\nkontakt@zipperwalls.de | www.zipperwalls.de",
      "button_text": "Messe planen und beraten lassen",
      "button_link": "https://www.zipperwalls.de/kontakt/",
      "extra_title": "Zum Nachlesen: alle Ratgeber an einem Ort",
      "extra_text": "Planung, Aufbau, Transport und Standgestaltung: Alle Artikel finden Sie gesammelt in unserem Wissensbereich.",
      "extra_link": "https://www.zipperwalls.de/wissen/",
      "image_idea": "Grafik aus Post 24 (KW 53).",
      "note": "Versand zwischen den Jahren: geringere Öffnungsrate zu erwarten. Alternative: auf Di 05.01.2027 verschieben und im Q1-Plan berücksichtigen.",
      "status": "Entwurf",
      "open_rate": null,
      "click_rate": null,
      "unsubscribes": null
    }
  ]
};
